version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=workflow
      - DB_HOST=database.local.work
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["./app"]

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - database.local.work

volumes:
  postgres_data: 