---
- name: Ensure /tmp/tools directory exists
  file:
    path: /tmp/tools
    state: directory
    mode: '0755'

- name: Copy install-docker.sh to remote host
  copy:
    src: install-docker.sh
    dest: /tmp/tools/install-docker.sh
    mode: '0755'

- name: Run install-docker.sh
  shell: /tmp/tools/install-docker.sh
  args:
    executable: /bin/bash

- name: Add multiple users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Configure Docker to ignore IPv6
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "ipv6": false
      }
    owner: root
    group: root
    mode: '0644'

- name: Restart docker.service
  shell: |
    systemctl enable docker
    systemctl start docker
