FROM golang:1.22-alpine
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY main.go .
COPY main_test.go .
RUN go mod download
RUN go install golang.org/x/lint/golint@latest
CMD ["/go/bin/golint", "./..."]